name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Ensure the directory exists on the server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2-USER }}@100.27.216.122 << 'EOF'
          mkdir -p /var/www/html/gynic/gynik
        EOF

    - name: Deploy code using rsync
      run: |
        rsync -avz --exclude='.git*' --exclude='node_modules/' ./ ${{ secrets.EC2_USER }}@100.27.216.122:/var/www/html/gynic/gynik/
      env:
        DEBUG: true  # Enable debugging to get detailed logs

    - name: Clean up
      run: |
        echo "Deployment completed successfully!"
